version: 2
jobs:
  build:
    machine: true

    steps:

      - checkout

      - run:
          name: compose_to_be_removed
          command: |
            cd stand
            docker-compose up
          background: true

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0


      - run:
          name: generator
          command: |
            dockerize -wait tcp://localhost:2003 -timeout 4m
            bash stand/generator.sh
          background: true


      - run:
          name: tmp1
          command: sleep 60

      - run:
          name: tmp2
          command: ls stand/data/clickhouse/data/

      - store_artifacts:
          path: stand/data/clickhouse/data/events/
