version: 2
jobs:

  build_demo_0:

    docker:
      - image: circleci/python:3.7.0

    steps:

      - checkout
      - setup_remote_docker


      - run:
          name: compose
          command: |
            cd stand
            docker-compose up
          background: true

      - run:
          name: generator
          command:  |
            docker build -t generator ./Generator
            docker run --network container:stand_clickhouse_1 generator

          background: true

      - run:
          name: image
          command:  |
            docker build -t image ./Image
            docker run --network container:stand_grafana_1: image

      - run:
          name: copy image
          command:  |
            docker cp image:/snapshots/output.png stand/snapshots/output.png


      - store_artifacts:
          path: stand/snapshots




  build_demo_2:

        docker:
           - image: circleci/python:3.7.0

        steps:

          - checkout
          - setup_remote_docker

          - run:
              name: compose
              command: |
                cd demo2
                ls
                docker-compose up
              background: true


          - run:
              name: generator
              command:  |
                docker build -t generator ./Generator
                docker ps
                docker run --network container:demo2_data-receiver_1 generator


workflows:
  version: 2
  demo0:
    jobs:
      - build_demo_0
#  demo1:
#    jobs:
#      - build_demo_1
  demo2:
    jobs:
      - build_demo_2
