clickhouse:
  image: yandex/clickhouse-server
  ports:
    - "8123:8123"
  volumes:
    - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
    - "./data/clickhouse/data:/var/lib/clickhouse/data"
    - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"

clickhouse-init:
    image: yandex/clickhouse-server
    volumes:
      - "./init.sql:/init.sql"
    entrypoint: |
      bash -c '
        sleep 5
        export HOME=/var/lib/clickhouse/
        cat /init.sql | clickhouse client --host clickhouse --multiquery'
    links:
      - clickhouse

data-receiver:
    build: reciver_python
    volumes:
      - "./reciver_python/read_data.py:/read_data.py"
      - "./res/results:/results"
    ports:
      - "2003:2003" # plain tcp
      - "2003:2003/udp" # plain udp
      - "2004:2004" # pickle
      - "2006:2006" # prometheus remote write
    entrypoint: python /read_data.py
    links:
      - clickhouse
